### ISSUE TITLE
Execute intents

### ISSUE THREAD

**Issue by PizlaTheDeveloper** [actions-on-google/smart-home-local#18] opened 2020-01-29 14:06 UTC
Hi,
I am working on integration of Google Smart Home services for our PLC system used in "smart homes". Now I am implementing the local execution path. Everything goes ok when I'm testing with usual number of emulated lights. But I wanted to make some boundary tests, so I emulated e.g. 30-100 lights. When I try to set them all using Google Home speaker, the local execution intent is processed and the promise is resolved in few seconds. It resolves even earlier then the speaker starts responding. But the response from the speaker is in 99% cases: "Device is not reachable...". The strange thing is, that in the same time when the local execution starts, it is processed the same execute intent using cloud fulfillment - is this some backup path if local device is not accessible? But why it is running concurrently? Are there any timeouts for resolving local execute intents?

Thank you

**Comment by devunwired** [comment] 2020-01-29 14:49
> When I try to set them all using Google Home speaker, the local execution intent is processed and the promise is resolved in few seconds. It resolves even earlier then the speaker starts responding. But the response from the speaker is in 99% cases: "Device is not reachable...".

Do you only encounter the issue when you try to set **all** of the lights at once, or does the same problem occur if you send a command for a single device or small number?

> The strange thing is, that in the same time when the local execution starts, it is processed the same execute intent using cloud fulfillment - is this some backup path if local device is not accessible?

There are two potential reasons for this:
1. Local execution does include cloud fallback. If the SDK receives an error or invalid response from the local command, it will attempt to the same command through the cloud path. Verify that your `EXECUTE` response is correct.
2. Not all of the end devices in the command group have been marked and identified for local execution, so both a local intent and cloud intent are sent. In this case you would see the intents target different specific devices. This will happen if not every device has `otherDeviceIds` reported via `SYNC` to Home Graph.

**Comment by PizlaTheDeveloper** [comment] 2020-01-29 15:14
> Do you only encounter the issue when you try to set all of the lights at once, or does the same problem occur if you send a command for a single device or small number?

Only when trying to set all of the lights at once. One light works fine.

> Verify that your EXECUTE response is correct.

I will check it again. But for small amount of devices or single device it works fine for me.

**Comment by PizlaTheDeveloper** [comment] 2020-01-30 09:34
Should be used `markPending` method of `DeviceManager` somehow in the case of time consuming execute request? Is there any example of using it?

**Comment by devunwired** [comment] 2020-01-31 17:43
Yes, you should be able to use `markPending()` if you're reasonably sure the command will succeed but the time required to execute is more than a few seconds. You still need to return an `Execute.Response` upon completion. Something like this:

```typescript
public executeHandler = async (executeRequest: smarthome.IntentFlow.ExecuteRequest):
    Promise<smarthome.IntentFlow.ExecuteResponse> => {

    // Acknowledge the command for TTS
    this.app.getDeviceManager().markPending(executeRequest);

    // Execute individual device commands
    const command = executeRequest.inputs[0].payload.commands[0];
    const executeResponse =  new smarthome.Execute.Response.Builder()
      .setRequestId(executeRequest.requestId);

    await Promise.all(command.devices.map(async (device) => {
      // ...
      try {
        const result = await this.app.getDeviceManager().send(...);
        executeResponse.setSuccessState(...);
      } catch (e) {
        executeResponse.setErrorState(...);
      }
    }));

    // Return completed execution response.
    return executeResponse.build();
  }
```

**Comment by PizlaTheDeveloper** [comment] 2020-01-31 20:05
Thank you for the example. You exactly described my implementation of execute handler. I have already estimated the use of the `markPending` method and tested it. But still got same results :/ When trying to set a big amount of lights (tested on 100 lights) I got EXECUTE intent on cloud fulfillment concurrently.

**Comment by devunwired** [comment] 2020-01-31 20:50
Let's separate out the two original issues:
1. Receiving "Device is not reachable..." user response
1. Seeing both cloud and local EXECUTE intent.

Did the example code with `markPending()` address either of them?

Regarding item 2, can you share the contents of each intent? Do the cloud and local EXECUTE request match, or are they for a different set of devices?

**Comment by PizlaTheDeveloper** [comment] 2020-01-31 21:59
I think that the "Device is not reachable..." issue was related only with my problem to process too many requests on the PLC's side caused by the concurrent execute intents made from cloud and the local speaker. I think that `markPending()` has no effect on behavior.

The requests match:

[cloud_exec_intent.txt](https://github.com/actions-on-google/smart-home-local/files/4141550/cloud_exec_intent.txt)
[local_exec_intent.txt](https://github.com/actions-on-google/smart-home-local/files/4141551/local_exec_intent.txt)

**Comment by devunwired** [comment] 2020-01-31 22:39
So then to clarify a previous response, the concurrent issue you are describing only happens with the large device group as well (doesn't happen with a single device command, for example)?

What does your `SYNC` response look like for these devices?
Are the devices all identified directly, or is your local PLC a device acting as a proxy and they are identified through `REACHABLE_DEVICES`?

**Comment by PizlaTheDeveloper** [comment] 2020-02-01 07:16
> So then to clarify a previous response, the concurrent issue you are describing only happens with the large device group as well (doesn't happen with a single device command, for example)?

Yes, look like the problem will appear when simulating > 50 lights. I don't know the exact boundary. But I think that maybe it is not problem with the amount, but with time needed to process the execute intent. I don't create one http request for each light for plc, but for optimization I create one large http request with set commands for all lights. It takes averagely 2s to process it for 100 lights. Can not be this problem? Have `setSuccessState()`, `setErrorState()` any special purpose for letting the process alive? Because they are called for each light after the 'large' http request is processed.

> Are the devices all identified directly, or is your local PLC a device acting as a proxy and they are identified through REACHABLE_DEVICES

PLC is identified as a proxy and simulated devices are identified through REACHABLE_DEVICES

**Comment by PizlaTheDeveloper** [comment] 2020-02-03 13:29
I have some new observation.
I think that the problem is related with assignment of devices to Home/Room in Google Home app.
If the devices are in the 'Linked to you' state (not assigned to any Home/Room), they are not local executable even if that they are reachable in REACHABLE_DEVICES intent. All execution are made using cloud fulfillment, no local intents are initiated. When assign any of the linked device to a Home/Room, local execution starts to be executed for all reachable devices. But due the fact, that some of the 'Linked to you' device is still not assigned, there will appear a cloud fulfillment execution request, but for all devices again. In my theory, If I assign all devices to a Home/Room, there will be not any cloud requests, but only locals. But I am unable to test it for a big amount of devices, because it is very complicated to assign a device to a Home/Room in Google Home app. There should be some option for assigning multiple devices. Not one by one :/

I do not know whether I explained it clearly :)

**Comment by PizlaTheDeveloper** [comment] 2020-02-04 14:17
Hi :)
I had a job with the placement of 50 lights to a room, but my previous theory is not confirmed. Still got simultaneous requests on local and cloud :/

**Comment by devunwired** [comment] 2020-05-02 20:11
I'm unable to reproduce this using the v1.0 SDK and this sample code and a virtual hub with 50 reachable lights (example below):

```
npm start --prefix device/ -- \
    --device_id hub1 \
    --discovery_protocol UDP \
    --control_protocol HTTP \
    --channel 1 \
    --channel 2 \
    --channel 3 \
    --channel 3 \
    --channel 4 \
    --channel 5 \
    --channel 6 \
    --channel 7 \
    --channel 8 \
    --channel 9 \
    --channel 10 \
    --channel 11 \
    --channel 12 \
    --channel 13 \
    --channel 14 \
    --channel 15 \
    --channel 16 \
    --channel 17 \
    --channel 18 \
    --channel 19 \
    --channel 20 \
    --channel 21 \
    --channel 22 \
    --channel 23 \
    --channel 24 \
    --channel 25 \
    --channel 26 \
    --channel 27 \
    --channel 28 \
    --channel 29 \
    --channel 30 \
    --channel 31 \
    --channel 32 \
    --channel 33 \
    --channel 34 \
    --channel 35 \
    --channel 36 \
    --channel 37 \
    --channel 38 \
    --channel 39 \
    --channel 40 \
    --channel 41 \
    --channel 42 \
    --channel 43 \
    --channel 44 \
    --channel 45 \
    --channel 46 \
    --channel 47 \
    --channel 48 \
    --channel 49 \
    --channel 50
```

I only see cloud `EXECUTE` when the local path fail and needs to fall back. Are you able to reproduce the behavior you're describing with the sample code in this repository?

**Comment by killvi** [comment] 2020-05-26 09:14
I have exactly the same issue, here i tried to reproduce it: https://github.com/killvi/actionOnAllLights.git

**Comment by proppy** [comment] 2020-08-03 03:37
Closing this as obsolete.

**Closed by proppy** 2020-08-03 03:37 UTC
