### ISSUE TITLE
Use local connection with proxy

### ISSUE THREAD

**Issue by zoic21** [actions-on-google/smart-home-local#1] opened 2019-07-11 15:30 UTC
Hello,

I tried to use local connection with hub but it does not work. I view IDENTIFY request, my response is : 
![image](https://user-images.githubusercontent.com/1536036/61063616-8a5fcc00-a400-11e9-8d05-14179a11aaa2.png)
This is my first question, why I need verificationId, doc say it's necessary but reference say it's optionnal (https://developers.google.com/actions/smarthome/reference/local/interfaces/smarthome.intentflow.identifyresponsepayload). For me in my case it's not need because I send isLocalOnly true (True if this device does not appear in the `SYNC response. This is common for hub devices.). So i device is not in SYNC response it's does not need a verificationId, no ?

After that I receveid REACHABLE_DEVICES, I said all device it's reachable (home is proxy for all my device in google home). 

After that I get "action.devices.PROXY_SELECTED", I don't know what I have to do with that... I can't find anything about that in documentation... I try to resend same response as REACHABLE_DEVICES and it's seem ok.

So according to the console all it's ok but I don't received any local execute exept if I test on verifcationId device.

Did anyone success with local api and hub systeme ?

Thank in advance for your reply

**Comment by proppy** [comment] 2019-07-12 04:18
Let me try to reproduce your issue, ideally we should also have a sample for the hub device (filed #2).

**Comment by zoic21** [comment] 2019-07-12 05:56
Thank I make some other try but I think I miss something...

**Comment by proppy** [comment] 2019-07-12 05:59
@zoic21 Did you manage to make the non-hub case work?

**Comment by zoic21** [comment] 2019-07-12 07:56
Yes for one device I make it work (I view execute command from google home hub). But I develop it for an home hub so I need proxy mode.

**Comment by proppy** [comment] 2019-07-17 20:16
@zoic21 can you confirm if your hub device is assigned to a Room?

**Comment by zoic21** [comment] 2019-07-18 07:45
Yes not all device but 90% of them are affected to room. For the hub I take first presented device from IDENTIFY and I say it's a hub and proxy. Maybe I need to create a specify device for this ?

**Comment by koush** [comment] 2019-07-24 21:42
I also get the proxy selected event, after which time it errors out. I took a look at the sdk code, and it’s possible to respond to it, but I’m unsure what to send back.

**Comment by zoic21** [comment] 2019-07-25 11:24
I have also PROXY_SELECTED but I can't find any documentation on it... I tried to resend same response as REACHABLE_DEVICES. No error but I it doesn't work...

**Comment by zoic21** [comment] 2019-07-25 16:30
I test also with :
![image](https://user-images.githubusercontent.com/1536036/61891586-44c7f680-af0a-11e9-9be9-a27413581e19.png)

Did not work...

**Comment by GatienB** [comment] 2019-07-26 17:28
I also get the same error
> smarthome.DeviceManager handle PROXY_SELECTED not implemented

**Comment by proppy** [comment] 2019-07-27 18:57
Managed to reproduce the issue:
```
Ready, App version: 0.0.1
bundle.js:288 Ready
app.ts:37 IDENTIFY request {requestId: "E425620A102646A3C9FD3F8EF9CF430D", inputs: Array(1), devices: Array(1)}
app.ts:37 IDENTIFY request {requestId: "3FA3DEF5A470BB9DA52E667F1396C17F", inputs: Array(1), devices: Array(1)}
app.ts:74 IDENTIFY response {intent: "action.devices.IDENTIFY", requestId: "E425620A102646A3C9FD3F8EF9CF430D", payload: {…}}
app.ts:74 IDENTIFY response {intent: "action.devices.IDENTIFY", requestId: "3FA3DEF5A470BB9DA52E667F1396C17F", payload: {…}}
smarthome_sdk.js:197  [ 56.980s] [smarthome.DeviceManager] Handler for REACHABLE_DEVICES not implemented 
smarthome_sdk.js:197  [ 57.007s] [smarthome.DeviceManager] Handler for PROXY_SELECTED not implemented 
```

Note that `PROXY_SELECTED` is triggered even if `REACHABLE_DEVICES` is not implemented (or fails)

**Comment by proppy** [comment] 2019-07-27 19:14
Adding:
```
smarthomeApp
    .onProxySelected((request: any) => {
        console.log("PROXY_SELECTED request", request);
        return {};
    });
```
Seems to workaround the failure.

**Comment by GatienB** [comment] 2019-07-29 08:34
It seems that `onProxySelected` doesn't exist.
Where and how should it be implemented ?

**Comment by proppy** [comment] 2019-07-29 09:36
@GatienB it does exists in the JS SDK, but it's not exposed thru the typescript typing.

Tracking the issue internal at b/https://github.com/actions-on-google/smart-home-local/issues/1#issuecomment-515706997
See:
https://github.com/actions-on-google/smart-home-local/issues/1#issuecomment-515706997

**Comment by GatienB** [comment] 2019-07-29 14:15
Thanks ! The error disappeared.
Are you able to control your device behind the hub ?

**Comment by zoic21** [comment] 2019-07-30 10:26
I test, no error but nothink work...

**Comment by GatienB** [comment] 2019-08-01 13:14
@proppy do you have any clue why it's still not working and how to solve it ?

**Comment by hardillb** [comment] 2019-09-08 19:17
Any update on this?

Do we have an ETA for an updated to the typescript types and doc for the SDK so we can get hub devices working?

**Comment by balloob** [comment] 2019-10-10 23:30
We have @home-assistant working as a hub device with the local SDK 💃 

I documented all the different interactions between Home Assistant and Google Assistant, including the quirks in the current implementation and incorrect types in the docs, to help the people in this issue 👍 [Find it here](https://github.com/NabuCasa/home-assistant-google-assistant-local-sdk/blob/master/REQUEST-RESPONSE.md)

If you want to try it out with Home Assistant, you will need to use this PR https://github.com/home-assistant/home-assistant/pull/27428

**Comment by proppy** [comment] 2019-10-11 00:59
@balloob thanks for working on that!

Let's work together one surfacing the issue you found in the [smarthome public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148)

**Comment by balloob** [comment] 2019-10-11 07:03
@proppy already reported it, b/142429438

**Comment by zoic21** [comment] 2019-10-11 09:12
Hello,
Googd news, but I try and it does not work... All it's ok in console, but I received only once REACHABLE_DEVICES (not every minute).
Weird stuff too on I do : 
`var reachablesDeviceHandler = function (request) {
  console.log('reachablesDeviceHandler : '+(new Date().toLocaleString())+' request : ',request);
  var reachables_devices = [];
  for(var i in request.devices){
    if(request.devices[i].id == 'fake-local'){
      continue;
    }
    reachables_devices.push({verificationId: request.devices[i].id});
  }
  console.log('reachables :',reachables_devices)
  var response = {
    intent: 'action.devices.REACHABLE_DEVICES',
    requestId: request.requestId,
    payload: {
      devices: reachables_devices
    }
  };
  console.log('response :',response)
  return response;
};`

But on my console.log I get : 
![image](https://user-images.githubusercontent.com/1536036/66639714-a9e0dd80-ec17-11e9-9510-f327e4822f48.png)
Why id instead of verificationId ?

Last thing, in documentation of home assistant I see "To trigger this intent, tell Google "force local" before saying a command.", but I am in french langage, I try "Force local #command#", "Force l'éxecution locale #commande#", nothcink work....

**Comment by balloob** [comment] 2019-10-11 15:18
Reachable devices need to return verificationId not Id. 

For force local, try putting your Google Assistant in English

**Comment by zoic21** [comment] 2019-10-11 18:23
Thanks for your réponse, i can't return verificationid, my code name Key correctly but something change key by id...

**Comment by gytisgreitai** [comment] 2019-10-27 10:14
Am I misunderstanding how this should work ? I'm using UDP discovery, and sending response as this:
```
{ 
  deviceId: 'openhab-local',
  port: 8089,
  itemPath: '/rest/items/'
}
```
Identify is called and it has this data in `request.inputs[0].payload.device.udpScanData` so kind of ok.

From identify handler I return this:
```
{
  intent: "action.devices.IDENTIFY",
  requestId: "1168E8DC3A64CD2BB3240DC270F0342D",
  payload: {
    device: {
       id: "openhab-local",
       isLocalOnly: true,
       isProxy: true
    }
  }
```
Now reachable devices handler is invoked with this request:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/1690228/67632972-c2592500-f8b2-11e9-9c69-7149937f3b78.png">

but `proxyData` is empty, though [docs about ProxyDevice state](https://developers.google.com/assistant/smarthome/reference/local/interfaces/smarthome.intentflow.proxydevice.html) that it has a member `udpScanData` which `Contains data if this result came from a UDP scan`

What am I missing?

**Comment by gytisgreitai** [comment] 2019-10-27 10:55
> Thanks for your réponse, i can't return verificationid, my code name Key correctly but something change key by id...

I think this is expected, if you look at minified smarthome_sdk.js source for some reason they are assigning  value to `id`and deleting `verificationId`

```
 var k = Sc(d, f);
      k
        ? ((f.id = k), delete f.verificationId, a.push(f))
        : console.error(
            "Failed to match device " + f + " with cloud synced devices "
          );
```

Though I must say this got me really confused while debugging...

**Comment by devunwired** [comment] 2019-11-01 16:29
Hey Folks, wanted to provide a quick update here. The current preview release has a few known issues in both the SDK and the platform firmware blocking proper testing and implementation of hub devices. We are working to get these addressed and they will be fixed in the next preview release. At that point we will be able to publish updates docs and samples regarding hubs.

We'll of course post an update when the updated preview is available.

**Comment by ufosaga** [comment] 2019-11-02 07:21
Hi @devunwired , thanks for the comment which will save a lot of time.

I noticed one issue for hub, in the identify stage, google home will trying to match the hub id to an unverified device (which is one of the otherDeviceIds in sync resp), however sync will normally not include any hub devices to the resp, so this should be fixed in the next preview. 

Please correct me if I misunderstood.

**Comment by ufosaga** [comment] 2019-11-02 07:33
Another one:
If the device is a hub, in the identify resp:
device.isLocalOnly: true
device.isProxy: true

these two field is documented well and are clear enough.

how about device.type? just ignore this field or use `action.devices.types.HUB` or something else?

**Comment by ufosaga** [comment] 2019-11-02 07:44
Related link #13 .

**Comment by devunwired** [comment] 2019-11-04 16:19
Hi @ufosaga 

> I noticed one issue for hub, in the identify stage, google home will trying to match the hub id to an unverified device (which is one of the otherDeviceIds in sync resp), however sync will normally not include any hub devices to the resp

You are correct, this is why we have to separate flags for `isProxy` and `isLocalOnly`:
- `isProxy`: This device is a proxy/hub that can reach other local devices
- `IsLocalOnly`: This device is not present in the SYNC response

A device that returns `isLocalOnly` during `IDENTIFY` will not be matched to one of the `otherDevicesIds` in `SYNC` (if you observe different behavior, please [file an issue](https://issuetracker.google.com/issues/new?component=655104&template=1284327)).

> These two fields are documented well and are clear enough. But how about device.type?

This field is optional and you can ignore it for your hubs. If appropriate for your device, you can set this field to one of the [device type](https://developers.google.com/assistant/smarthome/guides) strings.

**Comment by r-t-s** [comment] 2019-11-23 01:16
Is there still a bug in Execute for Hub type devices ? 
In identify I hardcoded my HubID (isProxy = true, isLocal = true)
In execute when I try to send (via DeviceManager) using the hardcoded HubID it says the device can not be found.

**Comment by r-t-s** [comment] 2019-11-25 05:16
Found my problem ... if I used the Proxied DeviceId, i.e. the DeviceId the command is sent to,  as opposed to the harcoded HubId, the Device Manager sent the info on to the hub. 

I was happy to see that traits with 2FA authentication was sent via the Local path witch because of common code,  returned an error that requested a PIN ... and the follow up execution was sent via the Cloud path.  So it is not quite as "BROKEN" as i though it might be.

**Comment by balloob** [comment] 2019-12-06 06:29
Yesterday cast firmware version 1.44.184686 got published to Google Home's on the preview channel (you can opt-in to this via Google Home app -> settings of a Google Home). It includes a bunch of bug fixes for the local SDK. We've been getting better results. The Google Home no longer restarts whenever we quit Home Assistant 👍 

Did notice one breaking change, and that's for mDNS data. Instead of `additionals` the data is now nicely parsed and ready to use 👍 

I've updated the request-responses that we see when interacting with the local SDK: [REQUEST-RESPONSE.md](https://github.com/NabuCasa/home-assistant-google-assistant-local-sdk/blob/master/REQUEST-RESPONSE.md). It also includes an example of an IDENTIFY intent with the new mDNS format.

**Comment by devunwired** [comment] 2019-12-13 17:44
We've updated this sample to include a hub use case, and included some additional detail in the [implementation guide](https://developers.google.com/assistant/smarthome/develop/local) for hubs.

Please note one item in the updated documentation, as @balloob mentioned, you have to opt your test devices into the **Cast Preview Program** to test this functionality with the latest Cast firmware, which has not rolled out yet to production devices.

**Closed by devunwired** 2019-12-13 17:44 UTC
Labels: b/137330475, b/138558072
